Finished UI Layout
chingu-voyages/v50-tier2-team-14 pull request #27
Opened 2024-08-08 07:14 UTC by Alvarado08

# Description
Finished application's desktop and mobile main UI layout.

## Main changes explained:
- Navbar: added state to logo click to open and close menu. This provides a quick and temporary way to show and hide the `Menu` component as we finish implementing the Leaflet map.
- Hero: added state to input arrow click to open and close menu. Exactly as the `Navbar` component logo click is working as explained above.
- About us
- How to order?
- Testimonials
- Footer

## How to test:
1. check into current branch
2. do `npm install` and `npm start` to run this PR locally
3. verify `Navbar` component logo click state and `HeroHome` component input arrow click state are displaying and hiding the menu correctly
4. verify section information and design for desktop and mobile

## Screenshots or videos of changes:
![Captura de Pantalla 2024-08-08 a la(s) 1 46 26 a m](https://github.com/user-attachments/assets/c249c140-dbda-40fe-b906-53e1aeb3b475)
![Captura de Pantalla 2024-08-08 a la(s) 1 46 36 a m](https://github.com/user-attachments/assets/79b85459-b2f8-497a-ae67-04477fd3daac)
![Captura de Pantalla 2024-08-08 a la(s) 1 46 54 a m](https://github.com/user-attachments/assets/73ca54bb-e104-48c3-8a30-bbc088dc55a4)
![Captura de Pantalla 2024-08-08 a la(s) 1 47 04 a m](https://github.com/user-attachments/assets/2507ded5-6932-4b59-89d2-8119d0b2f68f)
![Captura de Pantalla 2024-08-08 a la(s) 1 47 17 a m](https://github.com/user-attachments/assets/230e3aab-0c9e-4541-b61f-2a39b4f1b825)

## Note:
The show and hide menu is a temporary functionality just to give us an idea and quick use as we finish integrating Leaflet.

Any comments/suggestions are always welcome!

2024-08-08 14:17 UTC, cvtqx requested changes
Great work, Jorge! The page is responsive and makes a great homepage. I added some suggestions on text content. 
Other suggestions :

- center headers in mobile view and perhaps decrease the font size of headers in mobile view:

![Screenshot 2024-08-08 at 10 01 23 AM](https://github.com/user-attachments/assets/b9c8f4fb-fb42-44fd-b648-7ac770d80b29)

-Also in mobile view HeroHome component - image should be closer to the div with description, so the header is at the center of the screen

-Add alt prop to images - `alt='rabbit logo`' for example

2024-08-08 14:17 UTC, cvtqx commented on src/components/UI/HeroHome.js
> +            Offering a diverse menu that includes a vaiety of cuisines like
I think this paragraph does not convey the purpose of this app. This app is not a cafe but a food search app, so perhaps something like this would be more appropriate? -> **Find the best places to eat nearby! Just enter your location below to get started.**

2024-08-08 14:17 UTC, cvtqx commented on src/components/UI/About.js
> +          <div className="space-y-6 py-6">
These two paragraphs  do not convey the essence of this app, since it is not a cafe, but a food search app. In chat I think we agreed earlier to include a paragraph about the team: _We're a team of developers and UI/UX designer from all over the world who love two things: eating and coding. We've worked tirelessly to bring this app to life, and we hope you enjoy using it as much as we enjoyed creating it. Bon appétit and happy searching!_

2024-08-08 14:17 UTC, cvtqx commented on src/components/UI/HowTo.js
> +            <p className="font-light text-lg">"Select your residence"</p>
I suggest - 'Select your location' or 'Select your state'

2024-08-08 14:17 UTC, cvtqx commented on src/components/UI/HowTo.js
> +              "Select fast food or restaurant"
Step 2 in our process should be 'Select your food category' - because this is what the app does.

2024-08-08 14:17 UTC, cvtqx commented on src/components/UI/HowTo.js
> +            <p className="font-light text-lg">"Place your order"</p>
Step 3 is 'Select a restaurant'

2024-08-08 14:17 UTC, cvtqx commented on src/components/UI/HowTo.js
> +            <p className="font-light text-lg">"Out for delivery"</p>
Step 4 - 'Place your order' 
I think these 4 steps are how the user would use our app. Open to discussion of course!

2024-08-09 02:45 UTC, Alvarado08 commented
Thank you for taking the time to review and give some amazing feedback, Olga @cvtqx!

I have implemented the corresponding changes. Please `git pull` so you can have the latest commit.

2024-08-09 14:20 UTC, cvtqx approved these changes
Looks great! Thanks for the updates! Merging.

Mobile view:

![Screenshot 2024-08-09 at 10 19 01 AM](https://github.com/user-attachments/assets/75834b87-5f69-4098-ba40-9647205aac72)

2024-08-09 14:20 UTC, merged